#+TITLE: Gear Ratios
#+AUTHOR: Michael R. Mauger
#+DATE: <Fri Jun 14 23:04:00 EDT 2024>
#+STARTUP: showeverything inlineimages
#+OPTIONS: toc:nil
#+OPTIONS: ^:{}
#+OPTIONS: num:nil
#+AUTO_TANGLE: t

* Day 3: Gear Ratios ---

You and the Elf eventually reach a gondola lift station; he says the
gondola lift will take you up to the water source, but this is as far
as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a
problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look
of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't
working right now; it'll still be a while before I can fix it." You
offer to help.

The engineer explains that an engine part seems to be missing from the
engine, but nobody can figure out which one. If you can add up all the
part numbers in the engine schematic, it should be easy to work out
which part is missing.

The engine schematic (your puzzle input) consists of a visual
representation of the engine. There are lots of numbers and symbols
you don't really understand, but apparently any number adjacent to a
symbol, even diagonally, is a "part number" and should be included in
your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:

#+begin_example
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
#+end_example

In this schematic, two numbers are not part numbers because they are
not adjacent to a symbol: 114 (top right) and 58 (middle right). Every
other number is adjacent to a symbol and so is a part number; their
sum is 4361.

Of course, the actual engine schematic is much larger. What is the sum
of all of the part numbers in the engine schematic?

** Part Two

The engineer finds the missing part and installs it in the engine! As
the engine springs to life, you jump in the closest gondola, finally
ready to ascend to the water source.

You don't seem to be going very fast, though. Maybe something is still
wrong? Fortunately, the gondola has a phone labeled "help", so you
pick it up and the engineer answers.

Before you can explain the situation, she suggests that you look out
the window. There stands the engineer, holding a phone in one hand and
waving with the other. You're going so slowly that you haven't even
left the station. You exit the gondola.

The missing part wasn't the only issue - one of the gears in the
engine is wrong. A gear is any * symbol that is adjacent to exactly
two part numbers. Its gear ratio is the result of multiplying those
two numbers together.

This time, you need to find the gear ratio of every gear and add them
all up so that the engineer can figure out which gear needs to be
replaced.

Consider the same engine schematic again:

#+begin_example
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
#+end_example

In this schematic, there are two gears. The first is in the top left;
it has part numbers 467 and 35, so its gear ratio is 16345. The second
gear is in the lower right; its gear ratio is 451490. (The * adjacent
to 617 is not a gear because it is only adjacent to one part number.)
Adding up all of the gear ratios produces 467835.

What is the sum of all of the gear ratios in your engine schematic?


* Solution
Indexing of lists is not well supported, so we will use ~array~​s;
actually ~array~​s of ~array~​s—a matrix. So we will read the data file into
this two dimensional structure and process the data from there.

1. Read the data file
2. Identify symbol locations
3. Capture the digits surrounding the symbols
4. Calculate the sum of the digits

** Part Two
After identifying the symbol locations from part one, we will:
1. Capture the numbers around gear symbols
2. Filter out gears without only two numbers
3. Sum all the gear ratios

* Implementation

#+BEGIN_SRC scheme :tangle gear-ratios.scm :noweb no-export
  (use-modules (ice-9 rdelim))

  <<read-parts-matrix>>
  <<locate-symbols>>
  <<get-symbol-digits>>
  <<get-neighbor-digits>>
  <<calc-missing-part-number>>
  <<get-gear-ratios>>
  <<calc-sum-gear-ratio>>

  (define parts-file
    (let getopts ((args (cdr (command-line))))
      (if (null? args)
          "example.dat"
          (if (string=? "--" (car args))
              (getopts (cdr args))
              (car args)))))

  (define parts-matrix (read-parts-matrix parts-file))

  (format #t "Part One: Part number is ~s~%"
          (calc-missing-part-number
           (get-symbol-digits
            parts-matrix
            (locate-symbols parts-matrix))))

  (format #t "Part Two: Sum of the gear ratios is ~s~%"
          (calc-sum-gear-ratio
           (get-gear-ratios
            parts-matrix
            (locate-symbols parts-matrix))))
#+END_SRC

** Read the data file
Read the file as a list of strings and then transform it to a two
dimensional array.

#+NAME: read-parts-matrix
#+BEGIN_SRC scheme :tangle no :noweb no-export
  <<read-the-parts-file>>
  <<transform-into-parts-matrix>>

  (define (read-parts-matrix filename)
    (transform-into-parts-matrix
     (read-the-parts-file filename)))
#+END_SRC

*** Read the file as a list of strings
#+NAME: read-the-parts-file
#+BEGIN_SRC scheme :tangle no
  (define (read-the-parts-file filename)
    (let ((in (open-input-file filename)))
      (let next-line
          ((line (read-line in))
           (contents (list)))
        (cond
         ((eof-object? line)
          (close-port in)
          (reverse contents))
         (else
          (next-line
           (read-line in)
           (cons line contents)))))))
#+END_SRC

*** Transform the file into a two dimensional array
#+NAME: transform-into-parts-matrix
#+BEGIN_SRC scheme :tangle no
  (define (transform-into-parts-matrix list-of-strings)
    (let* ((nrows (length list-of-strings))
           (ncols (string-length (car list-of-strings))))
      (list->array '(0 0)
                   (map (lambda (line)
                          (map (lambda (ch)
                                 (cond ((char-numeric? ch)
                                        (- (char->integer ch) (char->integer #\0)))
                                       ((not (char=? ch #\.))
                                        ch)
                                       (else '())))
                               (string->list line)))
                        list-of-strings))))
#+END_SRC

** Identify Symbol locations
Scan the parts array and return a list of three elements: the symbol,
it's row (dim 1), and it's column (dim 2).

#+NAME: locate-symbols
#+BEGIN_SRC scheme :tangle no
  (define (locate-symbols parts-matrix)
    (let* ((shape (array-shape parts-matrix))
           (rows  (car shape))
           (cols  (cadr shape))
           (syms '()))
      (do ((r (car rows) (1+ r)))
          ((> r (cadr rows)))
        (do ((c (car cols) (1+ c)))
            ((> c (cadr cols)))
          (let ((cell (array-ref parts-matrix r c)))
            (when (char? cell)
              (set! syms (cons (list cell r c) syms))))))
      syms))
#+END_SRC

** Capture the digits surrounding the symbols
For each symbol, look at the 9 cell neighborhood of the symbol to
locate numbers. Add number to the list.

#+NAME: get-symbol-digits
#+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (get-symbol-digits parts-matrix symbols)
    (apply append
           (map (lambda (sym)
                  (get-neighbor-digits parts-matrix sym))
                symbols)))
#+END_SRC

*** Get numbers from the neighboring cells
For each symbol look at the run of digits directly above, below, left,
and right. The runs are combined into a decimal number. If there is no
run directly above (or below) then the runs on the corresponding
diagonals need to be checked.

#+NAME: get-neighbor-digits
#+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (get-neighbor-digits parts-matrix symbol)
    <<get-digit-run>>

    (let* ((n  (get-digit-run parts-matrix symbol -1  0))
           (e  (get-digit-run parts-matrix symbol  0 -1))
           (s  (get-digit-run parts-matrix symbol  1  0))
           (w  (get-digit-run parts-matrix symbol  0  1))
           ;; If nothing above, check the diagnals
           (ne (if (null? n)
                   (get-digit-run parts-matrix symbol -1 -1)
                   '()))
           (nw (if (null? n)
                   (get-digit-run parts-matrix symbol -1  1)
                   '()))
           ;; same for below
           (se (if (null? s)
                   (get-digit-run parts-matrix symbol  1 -1)
                   '()))
           (sw (if (null? s)
                   (get-digit-run parts-matrix symbol  1  1)
                   '())))
      (filter integer? (append ne n nw e w se s sw))))
#+END_SRC

*** Return a run of digits
If there is a digit at the specified location, try to gather all of
the digits before and after that location and convert that to a
number.

#+NAME: get-digit-run
#+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (get-digit-run parts-matrix symbol Δr Δc)
    <<get-matrix-item>>

    (let* ((sym-r (cadr symbol))
           (sym-c (caddr symbol))
           (r (+ sym-r Δr))
           (c (+ sym-c Δc)))
      (if (null? (get-matrix-item parts-matrix r c))
          '()
          (let find-start ((bc -1))
            (if (null? (get-matrix-item parts-matrix r (+ c bc)))
                (let find-end ((ec (1+ bc)) (num 0))
                  (let ((n (get-matrix-item parts-matrix r (+ c ec))))
                    (if (null? n)
                        (list num)
                        (find-end (1+ ec) (+ (* num 10) n)))))
                (find-start (- bc 1)))))))
#+END_SRC

*** Fetch an item from the matrix
#+NAME: get-matrix-item
    #+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (get-matrix-item matrix r c)
    (if (array-in-bounds? parts-matrix r c)
      (let ((val (array-ref parts-matrix r c)))
        (if (integer? val)
            val
            '()))
      '()))
    #+END_SRC


** Calculate the sum of the digits
#+NAME: calc-missing-part-number
#+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (calc-missing-part-number part-digits)
    (apply + part-digits))
#+END_SRC


** Get gears with two ratios
Capture the numbers around gear symbols and return them if there are
only two of them.

#+NAME: get-gear-ratios
#+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (get-gear-ratios parts-matrix symbols)
    (filter (lambda (gr) (= (length gr) 2))
            (map (lambda (gear)
                   (get-neighbor-digits parts-matrix gear))
                 (filter (lambda (sym) (char=? (car sym) #\*))
                         symbols))))
#+END_SRC

** Calculate the sum of gear ratios
#+NAME: calc-sum-gear-ratio
#+BEGIN_SRC scheme :tangle no :noweb no-export
  (define (calc-sum-gear-ratio gear-ratios)
    (define (apply* lst) (apply * lst))
    (apply + (map apply* gear-ratios)))
#+END_SRC


* Data

** Example data
#+BEGIN_SRC text :tangle example.dat
  467..114..
  ...*......
  ..35..633.
  ......#...
  617*......
  .....+.58.
  ..592.....
  ......755.
  ...$.*....
  .664.598..
#+END_SRC

** Example Data for Part Two
#+BEGIN_SRC text :tangle example2.dat
  467..114..
  ...*......
  ..35..633.
  ......#...
  617*......
  .....+.58.
  ..592.....
  ......755.
  ...$.*....
  .664.598..
#+END_SRC

** Input Data
#+BEGIN_SRC text :tangle input.dat
  ...733.......289..262.....520..................161.462..........450.........................183.............................................
  ....*....................*.............707.352....*............/.....................801...@...............333..196........484.635......287.
  ....42.........131....913..............*......&..........634..................440..&...............83.....@...........404$..=....*..423.*...
  618.......272....*.........&......547.344...............#............689.589.*....150......382=................................168......433.
  ..........=...............253.102*.........#......78.......804..........*........................858.........................-..............
  ...69.......*37...510.797...........596.946........#..................................602.175...............203..100..........681.......546.
  ...*.....110.....*......*..........*..........396......858=.......381....................*.......246*637..........=..391+...................
  ...973........274..551.............576.21@.......$..................*.......................................176............181.883......*...
  .......223............+............................649.701.936...17..482..........80...........210.......+...=.........563.......*...222....
  .373..*..................532....707.......956....@..+.....*......*...........+927.*......698......+....763.........275*.....27..498.........
  ....*......................+......*.........*..719....540.........24...=...........39...*...................514.........126..#..............
  .....974.......952*308..@..........965....450............*4.343......772../..............437............=....*............./.....309........
  ............58..........840.....34................877........$............189..................*186......657.670................&.......854.
  ....22.406..*......883............*......880...........939...................................58.....387..................*..................
  ......*....587.........564/......599.......*...........*......................831.891/...552..........$.534+.....%802.975.960.346*..........
  .792+..............828................-807.6...........326....324...722...334..*...........*................................................
  .....................*.......................895..764*.........=...*........*..611..........79.......461@..546*940...818.346..........247...
  ....%....473......................288.......*....................932.....590...........918......791..................................*......
  .....621...*........................*....129....425.10.....*.....................419....*.........*...166......#11...................831....
  119........302.832.............159.506................*.229.....493....39...............587....523.......*..........610...805.559...........
  ......971.......*..........229*..........961........139..................+....411..................554....26.90.....$........*....-.........
  ...........463.615...................315....#...................................-...422.......109.-............*247................231.56...
  ..279*159.*...........126...569...............906..20..........990..........27.........%.......*.............................960-......./...
  ...........364....812*.......*..$.........812*....*.....369....&......176......................15.346#...#.....908...828..........-650......
  .842*771....................189..9...............42...............897*...............479.................99.....+.......*...................
  ................842*356.849...............336.......201................412......./...@...........205....................956....*319.383*....
  ...438....&................*......../.......*.../...*....&.......62...*........348..............*....................54.....302.........298.
  ......$..318................264.....28...259..824..306...249.......&.392...444............889#..418....945...496..../.......................
  ................610.160......................................................%.699...987......................*.............................
  ..........@125.....*..............292..#....514..........................165....*...*....&.....*672.....551.194.426......53...500.599...278.
  .275.192.........................*....854..#..............190............$.....40..662.706..774.........$................../..*......*......
  ....*.........*840....*638.....82...................520...*................................................../.190...719.......34....620....
  ...........532.....521................................*...423..75..........+....-........#...29.......258.605.....*..-......................
  ...........................37........../354.%453.....248.........*...561.481....727....437........969...*......243..........................
  ..................................183.........................+..250...+...................312.....=....150............@...229..............
  ...624...454*710..../..........=..*......../........%30....308..............................*................+...381..941........461.341....
  ......=............19.........297.......213..........................%............*522......442............962...-............92..-.....*...
  .................................................324.663............775...290=.301...............=...15........=....780..................562
  747........................438...35...806*.......*......................................%396..508......*700...16..-..$..230....443..617.....
  .......$.........447......*...............336..424.........618........-..276......260............................452......#......*...*......
  ....824..@916....%...488..145....%.....55..........821.....#.....620.773....*116..*.......384............156.972................974..872....
  ...................=...........494.....*......609................*...............768..195..*......108/..........*......440..................
  ...187...........135.=.....44.........860..........$.......+..923...........966..........#..136.................423.......#....185..........
  .....*....298........761.........................217....157..................*.....................292....268........#........./............
  ..789........../.375.........919.......425.........................542.....691..69..........184......*.......*.....578............531.......
  .......740..619..*..............=........%....788.....+..324..........*..........*......531..*..=82....962.409.690..........981.............
  ......*...........652..+.........................*....32.#...........53...........761...*...353.....43*.......................*....6....611.
  ....589......../........190.362@....961...........917......*...........................165...............&..718...............633...*.......
  .............781...565...............*................&..324...............................339..........964..+..........%..........427..312.
  .........927.......*........#260......919.......828..469........585..........803............/...&.......................365.................
  ....406..........190........................308.*.................*.............*2.803&.........417....=............................955..126
  .....#...61.75.......149....293.768....678#......675............449.....@...............%...............347......301.....-.490.....*........
  ............*........*.........*.............751........................888..&..348..49.747.........................*.318..#....888.........
  ..........160......335.................455....*.......761...................564..*............*926...654...../....907................857....
  .....446.....................@....915.....&....639...=...........285..............567......862................731..............9........*...
  ..........513.............694..........$...............233..721.&................................806.....101.........729.......@.........292
  ...........*.....565..................329................*..*........137......$849...=773...........=...*.............*..+..........32......
  ...359.277..849.....*399..................274....535....348.950.....*...............................................553..607......../.......
  .....%.*.................*...146.564.818....*.....*................438..............343..945......85............162.........................
  ...#...67.374..*593.....740......*......*..553...795..664...$................493#....*............-...............*...971...................
  ...510.....+........843.......791..277.................*....958....................489..#.................*657.213.....*...610.....193......
  ........*......#....#.................#.......$..&12....531......167......659*...........521...157*....896...........503......+.......*241..
  257..171.245....959........................109................+...............454..................239...../................................
  ...*...............................................#..........203...%...&..............359.330.846........751...382.985&.........646$..#....
  ..624........453..................870......890#...662.............371..311...739..........*.......*.............*............=.........817..
  ..................................*....................250.....54............*......../..........182...........237.....261@.250.............
  ................743.......946.....943.....414#...80....@.........*..751............159..448..............91.............................&529
  683....@....370..............*........569..........$........131...........@34..........*....736.........*...434*929.........127.............
  ...*.110.....*....48..........644....*....467.................*...............92.....673.......*718.....697.............979.&...............
  .745.......503.......288..827.....911.......+.......79..290.191..........$....*....................................230..........517.........
  .........%.....551..=.....#...........192.....917..&............597...479.....316.743...%.........#................*........122..*..........
  ....529.461.../..............793.........*633..*.................%..................=.604.........320.......393..599.........*....717.......
  768...*...............=567.....-.144..............545................6....591..............216*.......73..*....*........215+.842............
  .....783....855............196......*.........909..*......537.......*......=....435............874.../...902.657........................@449
  .............*........%510........28..........*...605.....@.......468............#.....630........................418@..............701.....
  ......397.....748........../...+........487..521......934...................&992.....-.....160.......477.....-.......................*......
  .916.................476.651..462..........%...........*...464......................425....*...........*..531...735....=..878.....853.......
  ....*...............*.............*..................965...*.........754..3..657.......................92..........@..838...................
  .....116.....469...498........537..666....622&............237.......*..........*....204...........242.........&...............599=..........
  ..............-................../.............283=...........283#.919.........638.*.........452.....*794......204.326...................168
  ...........................541........................544.............../183........67..903+........................*....75.512..605........
  860..............*.........*.............455....730....*......................143................@....-.....=...366.......@......*...+59....
  ...*..............447....916.....127........+.....*.....60................./....*...............572.658...891...+...300.....674.733.........
  .768................................*.-..........522.28.......870.....-....89./......764*...........................*........%..............
  ............606....*...................798..............298...*......342......430........668.........485.270.265/..893..............=....524
  ......#.880*.......88..907.........239..........509....=......406.+..........................264........*................829........991.%...
  ....850.................%.....&913....*...........*...............302..&228.......%601....63*......414....*156.............&...310..........
  .............@....184.......=.......260..........748........................149................................895.....697.......*.66.......
  ..........483.......*....500..970.......88..941...........25.....623...436...*.....................278..........=......*......522..*........
  ................................*.........*.-.......885....*.......#....$..848........260.........-.....579.........950...........948.......
  ...........270..........+....$..736.....245.........*....936.512........................*...@..........*.....$.&.........790................
  .....................634...764....................488.........#......454...............46.995........344...59..135..........#.@851...@949...
  808.......214.............................................610...................................185*........................................
  ...........*.............+...........812........606..........*.................383..................218...355/................804.@687......
  .....751.476......145.....991.314.........................123.....917......434....*.634..&....@.................805....15......*............
  ......#......25......*884......*..@......526*.................*20....*....*.....328.$....672.245....*392.423$...-.....*......83....484.581..
  ..............................440.759............124*397...779.......752.303.....................764.................376.806......*....*....
  .401..976...75....765.......................%.......................................430...................................*......796....82..
  ........*...&......*......474...2.-351....287.....=........@.......%....%....*731......$.......=....976.........960#.381..192...............
  ........808........959.......#.....................322......243...534.134.828............*....95.........241...........*.......388...567....
  ....$.........511......435.........825..................................................742...............&........%....888...#.............
  ....53...........-....................$.......-...........................191.....933........454...................649..........=...........
  .....................993..430*....624........817.102.......660...............*.../.....157/...*...............................845...........
  .....&.....466..692.....*....../.....*.................987.........381....746..................744...........722.........340................
  ..526.........*...*......74..810....257.........-....../............*...........941..898..................../......769...=...480..$...@.....
  ........658...338.107..+.................563..550........388*....542.............+....&........112......572........&........*....553...588..
  631........#..........641..759......880.@....................740........247....................*...........*............$....310............
  ..........................@.........*.............888....&........-.....*....3....154....790..24..847/......767......933..............#.....
  .....790...684....669............626....324....@.......862......77..+....627..*......*....*.....................809*.............922..913...
  ......*.............*.....*243..................372..........+.......878.......155.36...656....%..........917.............#.....*...........
  ....935....184/....888.357.....917..797....293...............427............................665..766.........*.........986.......671........
  ................................*..................................93.247................$..........*641....598..........................459
  ........................922*295..664....&..........188%.481..............*.............35.............................806.......107*32..*...
  ..........261.$113.....................456...................916..480....942.848.....................781*3.146..168....*......=..........222
  137.......*.................243..............783*......940......*....*........*......155......*25...........*...$...902........217..........
  .../....460.....140..170.........................283..*......647...501...-.359...365.......491.........869..103.............................
  ...............*......$.........941..................75................282....../...............786*.....*......741.686......24.............
  527........................*109.*...522..................*79.....#575...............................810...373..*......*..444*...............
  ...*..&37...............331.................714*..............................62$...43..%.......................983.446.............79......
  886.............................................40.................506.421..............726............171...............676*964.....*......
  ................651#...301..500..497.......601*......%...263*675......*.......136*56..................*.............836...............264...
  ........229....................#...&...156.....495..769......................................597.......355.............#..365...379.........
  ....539.......%...933...................*..138..................402...730.......................*718.......12................$.*............
  ....*........63...*....................368.....691....................*..............................#...../.....772............116.........
  ....501............777.......673..728......613.&...467....688.../..526...387...726.......@568.260..456..............*.......64..............
  403...........................*.....................*.....*...311.......&.....*....387.........*.......437..$901...744.929..................
  ...*.......................825.........&...........867.........................994...@........346.......................*.............285...
  ....260........892*.................294..................................#............................................172.....730...........
  ........743........610.........954......44@.46....606$..................718......963.970.........863.....772..............*......*..........
  284.......*............950.....*..............@..................=.............*......%.............*425.../..=625.....479.305.331...-......
  ...*...139................*...976........32........-.............655..........233.373.....870..431..................................17......
  399...........820........844.........%....../744.353.&...................370........*......*...........@...135..700............*............
  ....*364.#....../....266...........295................486..........932..........98.311....319..........599....*.&.......98.#....202.........
  .........768.........*.........982...........................413....*....185.....+................637.......48...........*.132..............
  .....................239........*.....................551.......*38.111....*.@.....778...856*25........605...../....355.........230.........
  ...105..........*.............879........264....177.....*.783............839.682......*..............*.....-....756....*...415.*.....589-...
  .............438....................428....*.........465.....*194....................803....100...955.238..836.........767.%...555..........
  .....86....&........702........./..*.......363.........................=630.737#............%...........................................259.
  ......*....256.......*.......+..57..806.......................591*............................*348....829...................+460............
  .....................244....6.....................................789......................687..............................................
#+END_SRC
